basePath: /v2
definitions:
  structs.Item:
    properties:
      description:
        example: A random description
        type: string
      itemCode:
        example: AAA321
        type: string
      itemId:
        example: 1
        type: integer
      orderId:
        example: 1
        type: integer
      quantity:
        example: 10
        type: integer
    type: object
  structs.Order:
    properties:
      costumerName:
        example: Arif Kurniawa
        type: string
      items:
        items:
          $ref: '#/definitions/structs.Item'
        type: array
      orderAt:
        example: "2022-02-17T21:16:38.147532+07:00"
        type: string
      orderId:
        example: 1
        type: integer
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: Arif Kurniawan
    url: http://www.swagger.io/support
  description: This is Orders API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /order/{id}:
    delete:
      consumes:
      - application/json
      description: delete orders by ID
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: delete selected orders
      tags:
      - orders
    put:
      consumes:
      - application/json
      description: get details of all orders
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: GetOrders
      summary: get details list of all orders
      tags:
      - orders
  /orders:
    get:
      description: get details of all orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: GetOrder
      summary: get details list of all orders
      tags:
      - orders
    post:
      consumes:
      - application/json
      description: get details of all orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.Order'
      summary: get details list of all orders
      tags:
      - orders
swagger: "2.0"
